---
title: "R in Econometrics"
author: "Jasper Tai"
date: "12/5/2020"
output: pdf_document
---

```{r}
curve(dnorm(x),xlim = c(-4,4))
x = seq(2,4,0.01)
y = dnorm(x)
polygon(x,y,col = 'red')
```

```{r}
install.packages('AER')
library(AER)
data("CPSSWEducation")
```

```{r}
labor_model <- lm(earnings ~ education, data = CPSSWEducation)
confint(labor_model)
vcov <- vcovHC(labor_model, type = "HC1") # variance and covariance matix
sqrt(vcov) # Robust standard error on diagnoal
```

```{r}
# Fixed effect
fixed <- plm(fatal_rate ~ beertax, 
                    data = Fatalities,
                    index = c("state", "year"), 
                    model = "within")
random <- plm(fatal_rate ~ beertax, 
                    data = Fatalities,
                    index = c("state", "year"), 
                    model = "random")
phtest(fixed, random)
fatal_tefe_mod <- plm(fatal_rate ~ beertax, 
                      data = Fatalities,
                      index = c("state", "year"), 
                      model = "within", 
                      effect = "twoways")
# mandadory jail or community service?
Fatalities$punish <- with(Fatalities, factor(jail == "yes" | service == "yes", labels = c("no", "yes")))

# discretize the minimum legal drinking age
Fatalities$drinkagec <- cut(Fatalities$drinkage,
                            breaks = 18:22, 
                            include.lowest = TRUE, 
                            right = FALSE)

# set minimum drinking age [21, 22] to be the baseline level
Fatalities$drinkagec <- relevel(Fatalities$drinkagec, "[21,22]")

library(lmtest)
bptest(y ~ x1 + factor(country), data = Panel, studentize=F)
# H0: No presence of heteroskedasticity

# IV
cig_ivreg <- ivreg(log(packs) ~ log(rprice) | salestax, data = c1995)
                          
```
